[project]
name = "minfer"
version = "0.1.0"
description = "Minimal Python (decoder-only) LLM inference engine w/ Triton and CUDA kernels"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch >= 2.7.0",
    "triton >= 3.3.0 ; sys_platform == 'linux'",
    "gguf >= 0.16.0",
    "ninja >= 1.11.1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-randomly>=3.16.0",
]