[project]
name = "minfer"
version = "0.1.0"
description = "Minimal Python (decoder-only) LLM inference engine w/ Triton and CUDA kernels"
readme = "README.md"
requires-python = ">=3.13"
# might have to pull gguf from github main
dependencies = [
    "torch >= 2.7.0",
    "triton >= 3.3.0 ; sys_platform == 'linux'",
    "gguf >= 0.17.1",
    "ninja >= 1.11.1.4",
]

[build-system]
requires = [
    "setuptools >= 80.9.0",
    "torch >= 2.7.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-randomly>=3.16.0",
]